name: Application ON Push & PR DO Code check
on: [push, pull_request]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run static code analysis
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true

      - name: Dart Code Metrics
        uses: dart-code-checker/dart-code-metrics-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check formatting
        run: dart format . --set-exit-if-changed

      - name: Run tests
        run: |
          [ -d "test" ] && flutter test -r expanded || echo "Tests not found."
          # run tests if `test` folder exists

      - name: Check pubspec.lock
        run: git diff --exit-code pubspec.lock
